--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--disable-gpu-driver-bug-workarounds
--enable-accelerated-mjpeg-decode
--enable-accelerated-video
--enable-accelerated-video-decode
--password-store=kwallet6
--enable-features=AcceleratedVideoDecodeLinuxGL
--enable-features=VaapiVideoDecoder
--ozone-platform=wayland
