#! /bin/sh

#####################################################
#####################################################
##                                                 ##
##  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗  ##
##  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║  ##
##  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║  ##
##  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║  ##
##  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║  ##
##  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝  ##
##                                                 ##
#####################################################
#####################################################

bspc config border_width            3
bspc config window_gap              12
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 7

bspc config normal_border_color  "#4c566a"  #lightnight
bspc config focused_border_color "#81a1c1"  #frost3
bspc config active_border_color  "#ebcb8b"  #aurora yellow

bspc config split_ratio          0.5
bspc config single_monocle       true
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc config ignore_ewmh_focus false

~/.dotfiles/scripts/workspaces_multimonitor.sh &

bspc rule -a Google-chrome desktop='Web'
bspc rule -a Google-chrome-unstable desktop='Web'
bspc rule -a Firefox desktop='Web'
bspc rule -a Evolution desktop='Mail'
bspc rule -a Pidgin desktop='Chat'
bspc rule -a Slack desktop='Chat'
bspc rule -a discord desktop='Chat'
bspc rule -a Kodi desktop='Music'
bspc rule -a Virt-manager desktop='VM'
bspc rule -a Steam desktop='Etc3' state=floating follow=no
bspc rule -a Xmessage state=floating
bspc rule -a Blueman-manager state=floating

# Initialize focus mode, game mode and do not disturb to false
echo "false" > /tmp/bspwmfocusmode.dat
echo "false" > /tmp/game_mode.dat
echo "false" > /tmp/dnd.dat

# Determine if running on laptop by looking for battery
battery_path=/sys/class/power_supply/BAT0/capacity
if test -f "$battery_path"; then
  echo "true" > /tmp/laptop.dat
else
  echo "false" > /tmp/laptop.dat
fi

# Start/restart redshift and polybar
killall -q redshift
while pgrep -x redshift >/dev/null; do sleep 1; done
redshift-gtk &
~/.dotfiles/scripts/polybar.sh
