-- Hyprland configuration (Lua, Hyprland 0.55+ hl.* API).
-- Ported 1:1 from hyprland.conf, which stays as a frozen fallback until this
-- file has soaked (Hyprland only reads the .conf when no .lua exists).
-- API reference: /usr/share/hypr/stubs/hl.meta.lua

local home = os.getenv("HOME")
local confdir = home .. "/.config/hypr/"

------------------
---- MONITORS ----
------------------

-- monitors.conf stays a plain data file: it is the single source for eDP
-- mode/scale and is parsed by BOTH this section and the awk in
-- scripts/hypr-display-profile.sh. Its format is frozen (see its header).
-- Rule order is load-bearing: a later matching rule overrides earlier ones,
-- so the catch-all comes first — hl.monitor() calls are issued in file order.
local function apply_monitors()
    local rules = 0
    local f = assert(io.open(confdir .. "monitors.conf", "r"))
    for line in f:lines() do
        local stripped = line:gsub("#.*$", "")
        local body = stripped:match("^%s*monitor%s*=%s*(.-)%s*$")
        if body and body ~= "" then
            local fields = {}
            for field in (body .. ","):gmatch("(.-),") do
                fields[#fields + 1] = field:match("^%s*(.-)%s*$")
            end
            local spec = {
                output   = fields[1] or "",
                mode     = fields[2] or "preferred",
                position = fields[3] or "auto",
                scale    = fields[4] or "auto",
            }
            -- Trailing key,value pairs (e.g. bitdepth,10)
            for i = 5, #fields - 1, 2 do
                spec[fields[i]] = tonumber(fields[i + 1]) or fields[i + 1]
            end
            hl.monitor(spec)
            rules = rules + 1
        end
    end
    f:close()
    assert(rules > 0, "no monitor rules parsed")
end

local ok, err = pcall(apply_monitors)
if not ok then
    -- Degrade to "displays work, untuned" — same failure contract as the
    -- shell parser's preferred/scale-1 fallback.
    print("hyprland.lua: monitors.conf parse failed: " .. tostring(err))
    hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
end

---------------
---- INPUT ----
---------------

dofile(confdir .. "input.lua")

-------------
---- ENV ----
-------------

-- Session env is consolidated in config/uwsm/env (Qt/GTK/Ozone/backend hints).
-- ONLY cursor theme/size is duplicated here on purpose: it must be present at
-- Hyprland level too, kept identical to uwsm/env (canonical). Do not add other
-- hl.env() calls here — put non-cursor session env in config/uwsm/env instead.
hl.env("XCURSOR_THEME", "Nordic-cursors")
hl.env("XCURSOR_SIZE", "24")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Palette generated by scripts/generate-colors; dofile (not require) so a
-- hyprctl reload after apply-theme re-reads the file instead of hitting the
-- package.loaded cache.
local c = dofile(confdir .. "colors.lua")
local function rgb(hex) return "rgb(" .. hex .. ")" end

hl.config({
    cursor = {
        inactive_timeout = 0,
    },

    general = {
        gaps_in = 6,
        gaps_out = { top = 0, right = 12, bottom = 12, left = 12 },
        border_size = 3,
        col = {
            active_border = rgb(c.accent2),
            inactive_border = rgb(c.bg3),
        },
    },

    decoration = {
        rounding = 13,
        -- Blur "amount" is size * passes, but size over ~5 produces artifacts;
        -- for heavier blur raise passes instead.
        blur = {
            enabled = true,
            size = 3,
            passes = 3,
            new_optimizations = true,
        },
    },

    animations = {
        enabled = true,
    },

    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        vrr = 1,
    },

    -- Don't bitmap-upscale XWayland surfaces on a fractional-scale eDP-1 panel —
    -- that makes Qt4 (Segger Ozone) and other X11 apps look blurry. Apps render at
    -- native pixels; per-state Xft.dpi in hypr-monitor-hotplug keeps them correctly
    -- sized (96 docked; undocked = round(96 * eDP scale), per hypr-display-profile.sh).
    xwayland = {
        force_zero_scaling = true,
    },
})

-- Ported from the legacy animation=NAME,1,SPEED,default lines.
hl.animation({ leaf = "windows",    enabled = true, speed = 3,  bezier = "default" })
hl.animation({ leaf = "border",     enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "fadeIn",     enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1,  bezier = "default" })

---------------
---- RULES ----
---------------

-- XWayland popups/menus surface with empty class and title — don't blur them.
hl.window_rule({
    name  = "xwayland-popup-no-blur",
    match = { class = "^()$", title = "^()$" },
    no_blur = true,
})

hl.layer_rule({
    name  = "rofi",
    match = { namespace = "rofi" },
    blur = true,
    ignore_alpha = 0.3,
    animation = "fadeIn",
})
hl.layer_rule({
    name  = "swaync-notification",
    match = { namespace = "swaync-notification-window" },
    blur = true,
    ignore_alpha = 0.3,
})
hl.layer_rule({
    name  = "swaync-control-center",
    match = { namespace = "swaync-control-center" },
    blur = true,
    ignore_alpha = 0.3,
})

---------------
---- BINDS ----
---------------

local dsp = hl.dsp

-- Session
hl.bind("SUPER + SHIFT + Q", dsp.exit())
hl.bind("SUPER + CTRL + SHIFT + Q", dsp.exec_cmd("poweroff"))
hl.bind("SUPER + CTRL + SHIFT + R", dsp.exec_cmd("reboot"))
hl.bind("CTRL + ALT + L", dsp.exec_cmd("hyprlock"))

-- Programs
hl.bind("SUPER + SHIFT + RETURN", dsp.exec_cmd("kitty"))
hl.bind("SUPER + E", dsp.exec_cmd("dolphin"))
hl.bind("SUPER + P", dsp.exec_cmd("rofi -show drun"))

-- Windows
hl.bind("SUPER + C", dsp.window.close())
hl.bind("SUPER + SHIFT + C", dsp.exec_cmd("hyprctl activewindow -j | jq -r '.pid' | xargs kill -9"))
hl.bind("SUPER + S", dsp.window.float({ action = "on" }))
hl.bind("SUPER + T", dsp.window.float({ action = "off" }))
hl.bind("SUPER + F", dsp.window.fullscreen({ mode = "fullscreen" }))
hl.bind("SUPER + M", dsp.window.fullscreen({ mode = "maximized" }))
hl.bind("SUPER + SHIFT + D", dsp.exec_cmd(home .. "/.dotfiles/scripts/hypr-toggle-laptop-display"))

-- Focus
hl.bind("SUPER + H", dsp.focus({ direction = "left" }))
hl.bind("SUPER + L", dsp.focus({ direction = "right" }))
hl.bind("SUPER + K", dsp.focus({ direction = "up" }))
hl.bind("SUPER + J", dsp.focus({ direction = "down" }))

-- Move window
hl.bind("SUPER + SHIFT + H", dsp.window.move({ direction = "left" }))
hl.bind("SUPER + SHIFT + L", dsp.window.move({ direction = "right" }))
hl.bind("SUPER + SHIFT + K", dsp.window.move({ direction = "up" }))
hl.bind("SUPER + SHIFT + J", dsp.window.move({ direction = "down" }))

-- Mouse drag / resize
hl.bind("SUPER + mouse:272", dsp.window.drag(), { drag = true })
hl.bind("SUPER + mouse:273", dsp.window.resize(), { drag = true })

-- Workspaces: SUPER+N focuses on current monitor, SUPER+SHIFT+N moves silently
for i = 1, 10 do
    local key = i % 10 -- SUPER+0 maps to workspace 10
    hl.bind("SUPER + " .. key, dsp.focus({ workspace = i, on_current_monitor = true }))
    hl.bind("SUPER + SHIFT + " .. key, dsp.window.move({ workspace = i, follow = false }))
end

-- Brightness
hl.bind("XF86MonBrightnessDown", dsp.exec_cmd("xbacklight -dec 10 -time 200 -steps 10"))
hl.bind("XF86MonBrightnessUp",   dsp.exec_cmd("xbacklight -inc 10 -time 200 -steps 10"))
hl.bind("SHIFT + XF86MonBrightnessDown", dsp.exec_cmd("xbacklight -dec 5 -time 200 -steps 10"))
hl.bind("SHIFT + XF86MonBrightnessUp",   dsp.exec_cmd("xbacklight -inc 5 -time 200 -steps 10"))

-- Audio
hl.bind("XF86AudioLowerVolume", dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -5%"))
hl.bind("XF86AudioRaiseVolume", dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +5%"))
hl.bind("XF86AudioMute",        dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"))

-- Lid switch (disabled, kept from the hyprlang config)
-- hl.bind("switch:Lid Switch", dsp.exec_cmd("hyprlock"), { locked = true })
-- hl.bind("switch:on:Lid Switch", dsp.exec_cmd("hyprctl keyword monitor \"eDP-1, disable\""), { locked = true })
-- hl.bind("switch:off:Lid Switch", dsp.exec_cmd("hyprctl keyword monitor \"eDP-1, 2560x1440, 0x0, 1\""), { locked = true })

-------------------
---- AUTOSTART ----
-------------------

-- HYPR_NO_AUTOSTART=1 skips autostart so a nested test session
-- (Hyprland --config .../hyprland.lua) doesn't double-launch daemons or
-- clobber the live session's eww bars.
if os.getenv("HYPR_NO_AUTOSTART") ~= "1" then
    hl.on("hyprland.start", function()
        -- hl.exec_cmd(home .. "/.dotfiles/scripts/launchportals.sh")
        hl.exec_cmd(home .. "/.dotfiles/scripts/islaptop.sh")
        hl.exec_cmd("uwsm app -- hyprpaper")
        hl.exec_cmd("uwsm app -- swaync")
        hl.exec_cmd("uwsm app -- nm-applet")
        hl.exec_cmd("uwsm app -- gammastep-indicator")
        hl.exec_cmd("uwsm app -- blueman-applet")
        hl.exec_cmd("/usr/lib/geoclue-2.0/demos/agent")
        hl.exec_cmd("uwsm app -- udiskie")
        hl.exec_cmd("pactl load-module module-switch-on-connect")
        hl.exec_cmd("uwsm app -- hypridle")
        hl.exec_cmd(home .. "/.dotfiles/scripts/hypr-monitor-hotplug")
        hl.exec_cmd(home .. "/.dotfiles/scripts/launch-eww-bars")
    end)
end
