# Input configuration (keyboard layout/options, sensitivity, touchpad)
# Sourced by hyprland.conf. App-owned: written by the settings app; keep it small.
input {
    kb_layout=us,se
    kb_variant=
    kb_model=
    kb_options=grp:win_space_toggle,caps:escape
    kb_rules=

    sensitivity=0.3
    follow_mouse=1

    touchpad {
        natural_scroll=true
        tap-to-click=true
        scroll_factor=1.0
    }
}
