#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Fix scaling

export GDK_SCALE=1
export GDK_DPI_SCALE=1

export QT_QPA_PLATFORMTHEME=gtk2
export DESKTOP_SESSION=gnome

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

laptop=`cat /tmp/laptop.dat`
if [ "$laptop" = true ]; then
    # For gnome-keyring (used by Evolution)
    eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
    export SSH_AUTH_SOCK

    xmodmap ~/.dotfiles/other/escremap
    autorandr --skip-options gamma --change
    xcalib -o eDP-1 ~/.dotfiles/other/B140QAN02_0.icm
    xbacklight -ctrl tpacpi::kbd_backlight -set 100
    libinput-gestures-setup start
fi

setxkbmap us
/usr/lib/geoclue-2.0/demos/agent &
feh --bg-fill $HOME/Pictures/wallpaper/11.png
picom --config ~/.config/picom/picom.conf -b
xsetroot -cursor_name left_ptr
xss-lock -- sxlock -f "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso8859-1" &
nm-applet &
headset-charge-indicator --headsetcontrol-binary /usr/bin/headsetcontrol &
blueman-applet &
/usr/lib/nordtray/nordtray &
dunst &
sxhkd &
udiskie &
aw-server &
aw-watcher-afk &
aw-watcher-window &
spotify-listener &
sleep 1
exec bspwm
