################################                        
################################
##                            ##
##  ███████╗███████╗██╗  ██╗  ##
##  ╚══███╔╝██╔════╝██║  ██║  ##
##    ███╔╝ ███████╗███████║  ##
##   ███╔╝  ╚════██║██╔══██║  ##
##  ███████╗███████║██║  ██║  ##
##  ╚══════╝╚══════╝╚═╝  ╚═╝  ##
##                            ##
################################                        
################################                        

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
ZSH=/usr/share/oh-my-zsh/

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
POWERLEVEL9K_MODE=nerdfont-fontconfig
ZSH_THEME="powerlevel9k/powerlevel9k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  colored-man-pages
  zsh-syntax-highlighting
  zsh-autosuggestions
  vi-mode
)


# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

export KEYTIMEOUT=1
export VISUAL=nvim
export EDITOR="$VISUAL"
export LESSOPEN="| /usr/bin/source-highlight-esc.sh %s"
export LESS="-R "
export BAT_THEME="Nord"
export DIFFPROG="nvim -d"

ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

source $ZSH/oh-my-zsh.sh
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
source ~/.zsh_local_additions

# Command aliases
alias grep="grep --color=auto"
alias dmesg="dmesg --color=always"
alias ls='exa --git --icons'
alias la='exa -lahg --git --icons'
alias ll='exa -lhg --git --icons'
alias lt='exa -T --icons'
alias ytop='ytop -p -s'
alias icat='kitty +kitten icat'

# Config aliases
alias vim="nvim"
alias vimdiff="nvim -d"
alias bspwmrc="vim ~/.config/bspwm/bspwmrc"
alias comptonconf="vim ~/.config/compton.conf"
alias conkyconf="vim ~/.config/conky/conky.conf"
alias dunstrc="vim ~/.config/dunst/dunstrc"
alias polybarconf="vim ~/.config/polybar/config"
alias roficonf="vim ~/.config/rofi/config"
alias sxhkdrc="vim ~/.config/sxhkd/sxhkdrc"
alias vimrc="vim ~/.vimrc"
alias xinitrc="vim ~/.xinitrc"
alias xresouces="vim ~/.Xresources"
alias zathurarc="vim ~/.config/zathura/zathurarc"
alias zshrc="vim ~/.zshrc"

# Functions
gvim() {
  neovide --multiGrid --disowned "$1" &
  disown
}

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'
ZSH_HIGHLIGHT_STYLES[suffix-alias]=fg=blue,underline
ZSH_HIGHLIGHT_STYLES[precommand]=fg=blue,underline
ZSH_HIGHLIGHT_STYLES[arg0]=fg=blue

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir vcs virtualenv)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vi_mode background_jobs)
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='grey'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='grey'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='grey'
POWERLEVEL9K_OS_ICON_BACKGROUND='grey'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="↳ "
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=""
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=""
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=""
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=""

bindkey '^ ' autosuggest-accept
bindkey '^R' history-incremental-search-backward
bindkey '^[[Z' reverse-menu-complete

#neofetch
